site_name: MGBA Setup Guide
site_url: https://al0102.github.io/mGBA-Guide/
nav:
  - Home: index.md
  - Getting Started: pages/getting-started.md
  - Configuring Audio & Video: pages/audiovideo.md
  - Configuring Controller & Keyboard: pages/configuring-controls.md
  - Rom Hacks: pages/romhacks.md
  - Troubleshooting: pages/troubleshooting.md
  - Glossary: pages/glossary.md


theme:
  name: material
  font:
    text: Lexend
    code: Lexend
  icon:
    logo: fontawesome/solid/gamepad
    favicon: assets/favcion.ico
  palette:
    # Auto mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/weather-night
        name: To Dark Mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: purple
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: To Light Mode

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: purple
      accent: deep purple
      toggle:
        icon: material/eye
        name: To Auto Mode
  features:
    # navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
    # footer
    - navigation.footer

markdown_extensions:
  # Contents navigation
  - toc:
      toc_depth: 3
  # Annotations
  - admonition
  - pymdownx.details
  # Emojis
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  # Checklist icon
  - pymdownx.tasklist:
      custom_checkbox: true
  # Code blocks
  # Code blocks syntax highlighting
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # Code block tabs
  - pymdownx.tabbed:
      alternate_style: true


# Footer
#   extra:
#     social:
# Add stuff here
